
export const ENGLISH_VOCABULARY_LIST = [
  { id: 1, word: "impervious", partOfSpeech: "adj.", definition: "unable to be affected by" },
  { id: 2, word: "incendiary", partOfSpeech: "adj.", definition: "1. tending to stir up conflict 2. designed to cause fires" },
  { id: 3, word: "incompetent", partOfSpeech: "adj.", definition: "not having or showing the necessary skills to do something successfully" },
  { id: 4, word: "inconceivable", partOfSpeech: "adj.", definition: "not capable of being imagined or grasped mentally" },
  { id: 5, word: "indissoluble", partOfSpeech: "adj.", definition: "solid, not able to be broken apart" },
  { id: 6, word: "inevitable", partOfSpeech: "adj.", definition: "certain to happen; unavoidable" },
  { id: 7, word: "infer", partOfSpeech: "v.", definition: "deduce or conclude (information) from evidence and reasoning rather than from clear statements" },
  { id: 8, word: "integrate", partOfSpeech: "v.", definition: "combine one thing with another so that they become a whole" },
  { id: 9, word: "intuition", partOfSpeech: "n.", definition: "the ability to understand something immediately, a 'gut feeling'" },
  { id: 10, word: "justify", partOfSpeech: "v.", definition: "show or prove to be right or reasonable" },
  { id: 11, word: "lack", partOfSpeech: "v.", definition: "be without or deficient in" },
  { id: 12, "word": "latent", "partOfSpeech": "adj.", "definition": "existing but not yet developed or obvious; hidden; concealed" },
  { id: 13, "word": "lethargic", "partOfSpeech": "adj.", "definition": "sluggish and apathetic" },
  { id: 14, "word": "mere", "partOfSpeech": "adj.", "definition": "used to emphasize how small or insignificant someone or something is" },
  { id: 15, "word": "minute", "partOfSpeech": "adj.", "definition": "extremely small (pronouned MY-noot)" },
  { id: 16, "word": "mishap", "partOfSpeech": "n.", "definition": "an unlucky accident" },
  { id: 17, "word": "nostalgia", "partOfSpeech": "n.", "definition": "a sentimental longing or affection for the past" },
  { id: 18, "word": "notion", "partOfSpeech": "n.", "definition": "a conception of or belief about something" },
  { id: 19, "word": "obsolete", "partOfSpeech": "adj.", "definition": "no longer produced or used; out of date" },
  { id: 20, "word": "obstruct", "partOfSpeech": "v.", "definition": "to be or get in the way of; prevent; hinder" },
  { id: 21, "word": "omit", "partOfSpeech": "v.", "definition": "leave out or exclude (someone or something), either intentionally or forgetfully" },
  { id: 22, "word": "orient", "partOfSpeech": "v.", "definition": "align or position something relative to a known point or landmark" },
  { id: 23, "word": "paradox", "partOfSpeech": "n.", "definition": "an idea that leads to a conclusion that seems senseless, logically unacceptable, or self-contradictory" },
  { id: 24, "word": "pensive", "partOfSpeech": "adj.", "definition": "engaged in, involving, or reflecting deep or serious thought" },
  { id: 25, "word": "peril", "partOfSpeech": "n.", "definition": "serious and immediate danger" },
  { id: 26, "word": "perpetual", "partOfSpeech": "adj.", "definition": "occurring repeatedly; so frequent as to seem endless and uninterrupted" },
  { id: 27, "word": "ponder", "partOfSpeech": "v.", "definition": "think about something carefully" },
  { id: 28, "word": "potent", "partOfSpeech": "adj.", "definition": "having great power, influence, or effect" },
  { id: 29, "word": "precede", "partOfSpeech": "v.", "definition": "come before (something) in time, order, or position" },
  { id: 30, "word": "predate", "partOfSpeech": "v.", "definition": "exist or occur at a date earlier than something" }
];
